# Generated by Django 4.2.6 on 2023-10-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('gateway_id', models.AutoField(db_column='GATEWAY_ID', primary_key=True, serialize=False)),
                ('gateway_address', models.CharField(db_column='GATEWAY_ADDRESS', max_length=8, unique=True)),
                ('gateway_nombre', models.CharField(db_column='GATEWAY_NOMBRE', max_length=16, unique=True)),
                ('gateway_latitud', models.CharField(db_column='GATEWAY_LATITUD', max_length=25)),
                ('gateway_longitud', models.CharField(db_column='GATEWAY_LONGITUD', max_length=25)),
                ('gateway_ubicacion', models.CharField(db_column='GATEWAY_UBICACION', max_length=100)),
                ('gateway_ntrasmisiones', models.IntegerField(db_column='GATEWAY_NTRASMISIONES')),
                ('gateway_nactividad', models.IntegerField(db_column='GATEWAY_NACTIVIDAD')),
                ('gateway_nfalla', models.IntegerField(db_column='GATEWAY_NFALLA')),
                ('gateway_password', models.CharField(db_column='GATEWAY_PASSWORD', max_length=32)),
            ],
            options={
                'db_table': 'gateway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcasMedidores',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marcas_medidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelosMedidores',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'modelos_medidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modulo_id', models.AutoField(db_column='MODULO_ID', primary_key=True, serialize=False)),
                ('modulo_address', models.CharField(db_column='MODULO_ADDRESS', max_length=8, unique=True)),
                ('modulo_tipo', models.IntegerField(db_column='MODULO_TIPO')),
                ('modulo_factor', models.FloatField(blank=True, db_column='MODULO_FACTOR', null=True)),
                ('modulo_calle', models.CharField(db_column='MODULO_CALLE', max_length=100)),
                ('modulo_numero', models.CharField(db_column='MODULO_NUMERO', max_length=10)),
                ('modulo_letra', models.CharField(blank=True, db_column='MODULO_LETRA', max_length=10, null=True)),
                ('modulo_piso', models.CharField(blank=True, db_column='MODULO_PISO', max_length=10, null=True)),
                ('modulo_puerta', models.CharField(blank=True, db_column='MODULO_PUERTA', max_length=10, null=True)),
                ('modulo_localidad', models.CharField(db_column='MODULO_LOCALIDAD', max_length=100)),
                ('modulo_departamento', models.CharField(db_column='MODULO_DEPARTAMENTO', max_length=45)),
                ('modulo_region', models.CharField(db_column='MODULO_REGION', max_length=45)),
                ('modulo_sector', models.CharField(db_column='MODULO_SECTOR', max_length=45)),
                ('modulo_latitud', models.CharField(db_column='MODULO_LATITUD', max_length=25)),
                ('modulo_longitud', models.CharField(db_column='MODULO_LONGITUD', max_length=25)),
                ('modulo_punto_en_plano', models.IntegerField(db_column='MODULO_PUNTO_EN_PLANO')),
                ('modulo_cliente', models.CharField(db_column='MODULO_CLIENTE', max_length=100)),
                ('modulo_suministro', models.CharField(db_column='MODULO_SUMINISTRO', max_length=45)),
                ('modulo_cuenta', models.CharField(db_column='MODULO_CUENTA', max_length=45)),
                ('modulo_medidor_numero', models.CharField(db_column='MODULO_MEDIDOR_NUMERO', max_length=45, unique=True)),
                ('modulo_medidor_marca', models.CharField(db_column='MODULO_MEDIDOR_MARCA', max_length=45)),
                ('modulo_medidor_modelo', models.CharField(db_column='MODULO_MEDIDOR_MODELO', max_length=45)),
                ('modulo_medidor_diametro', models.CharField(db_column='MODULO_MEDIDOR_DIAMETRO', max_length=4)),
                ('modulo_ultima_lectura_fyh', models.DateTimeField(blank=True, db_column='MODULO_ULTIMA_LECTURA_FYH', null=True)),
                ('modulo_ultima_lectura_valor', models.IntegerField(blank=True, db_column='MODULO_ULTIMA_LECTURA_VALOR', null=True)),
                ('modulo_alarmas', models.CharField(blank=True, db_column='MODULO_ALARMAS', max_length=8, null=True)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('id_parent', models.PositiveIntegerField(blank=True, null=True)),
                ('menu', models.CharField(max_length=1)),
                ('jerarquia', models.PositiveIntegerField()),
                ('is_sub', models.CharField(max_length=1)),
                ('mostrar', models.CharField(max_length=1)),
                ('mostrar_ose', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trasmisiones',
            fields=[
                ('trasmisiones_id', models.AutoField(db_column='TRASMISIONES_ID', primary_key=True, serialize=False)),
                ('trasmisiones_gateway', models.IntegerField(blank=True, db_column='TRASMISIONES_GATEWAY', null=True)),
                ('trasmisiones_signal', models.CharField(db_column='TRASMISIONES_SIGNAL', max_length=5)),
                ('trasmisiones_fyh', models.DateTimeField(db_column='TRASMISIONES_FYH')),
                ('trasmisiones_nlecturas', models.IntegerField(db_column='TRASMISIONES_NLECTURAS')),
                ('trasmisiones_lecturas_mod0', models.IntegerField(db_column='TRASMISIONES_LECTURAS_MOD0')),
                ('trasmisiones_lecturas_mod1', models.IntegerField(db_column='TRASMISIONES_LECTURAS_MOD1')),
                ('trasmisiones_lecturas_mod2', models.IntegerField(db_column='TRASMISIONES_LECTURAS_MOD2')),
            ],
            options={
                'db_table': 'trasmisiones',
                'managed': False,
            },
        ),
    ]
